{% set name = "napari-splinedist" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-splinedist-{{ version }}.tar.gz
  sha256: 4d0d8f128b1b922cf7f7b0a8a984940617919b1324c5d422a9c55098c0247d06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
  run:
    - magicgui
    - napari
    - napari-splineit >=0.3.0
    - numpy
    - opencv
    - pydantic
    - python >=3.8
    - qtpy
    - requests
    - stardist >=0.8.3
    - splinedist >=0.1.2
    - tensorflow

test:
  imports:
    - napari_splinedist
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python...
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-splinedist
  summary: A napari SplineDist plugin
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/DerThorsten/napari-splinedist

extra:
  recipe-maintainers:
    - DerThorsten
    - goanpeca
    - jaimergp
